# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/msm8974-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter msm8974,$(TARGET_BOARD_PLATFORM)),)

endif
