# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/jactivelte/setup-makefiles.sh

# DRM
PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/DRM/bin/qseecomd:system/bin/qseecomd \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libdrmdecrypt.so:system/lib/libdrmdecrypt.so \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libdrmfs.so:system/lib/libdrmfs.so \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libdrmtime.so:system/lib/libdrmtime.so \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libhdcp2.so:system/lib/libhdcp2.so \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libWVStreamControlAPI_L1.so:system/lib/libWVStreamControlAPI_L1.so \
        vendor/samsung/jactivelte/proprietary/DRM/lib/libwvm.so:system/lib/libwvm.so
