# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/trltespr/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/trltespr/proprietary/vendor/firmware/BT_FW_BCM4358A1_001.002.005.0032.0066.hcd:system/vendor/firmware/BT_FW_BCM4358A1_001.002.005.0032.0066.hcd \
    vendor/samsung/trltespr/proprietary/vendor/firmware/bcm43569.hcd:system/vendor/firmware/bcm43569.hcd \
    vendor/samsung/trltespr/proprietary/vendor/firmware/bcm43569A0.hcd:system/vendor/firmware/bcm43569A0.hcd \
    vendor/samsung/trltespr/proprietary/vendor/firmware/bcm43569A1.hcd:system/vendor/firmware/bcm43569A1.hcd \
    vendor/samsung/trltespr/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libalarmservice_jni.so:system/vendor/lib/libalarmservice_jni.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/liblbs_core.so:system/vendor/lib/liblbs_core.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/liblocationservice.so:system/vendor/lib/liblocationservice.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libulp2.so:system/vendor/lib/libulp2.so \
    vendor/samsung/trltespr/proprietary/vendor/firmware/sec_s3fwrn5_firmware.bin:system/vendor/firmware/sec_s3fwrn5_firmware.bin \
    vendor/samsung/trltespr/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/trltespr/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/trltespr/proprietary/bin/ks:system/bin/ks \
    vendor/samsung/trltespr/proprietary/bin/mdm_helper:system/bin/mdm_helper \
    vendor/samsung/trltespr/proprietary/bin/mdm_helper_proxy:system/bin/mdm_helper_proxy \
    vendor/samsung/trltespr/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/trltespr/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/trltespr/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/trltespr/proprietary/bin/rmnetcli:system/bin/rmnetcli \
    vendor/samsung/trltespr/proprietary/lib/libcfiril.so:system/lib/libcfiril.so \
    vendor/samsung/trltespr/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/trltespr/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/trltespr/proprietary/lib/librmnetctl.so:system/lib/librmnetctl.so \
    vendor/samsung/trltespr/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/trltespr/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/trltespr/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/trltespr/proprietary/lib/librilswitch.so:system/lib/librilswitch.so \
    vendor/samsung/trltespr/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libtime_genoff.so:system/vendor/lib/libtime_genoff.so \
    vendor/samsung/trltespr/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so
