# This file is generated by device/samsung/apq8084-common/setup-makefiles.sh

# Pick up overlay for features that depend on non-open-source files
PRODUCT_PACKAGES += \
    libtime_genoff \
    TimeService

$(call inherit-product, vendor/samsung/apq8084-common/apq8084-common-vendor-blobs.mk)
