# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/expressatt/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	vendor/samsung/expressatt/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
	vendor/samsung/expressatt/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
	vendor/samsung/expressatt/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
	vendor/samsung/expressatt/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
	vendor/samsung/expressatt/proprietary/lib/libril.so:system/lib/libril.so \
	vendor/samsung/expressatt/proprietary/bin/netmgrd:system/bin/netmgrd \
	vendor/samsung/expressatt/proprietary/bin/sec-ril:system/bin/sec-ril \
	vendor/samsung/expressatt/proprietary/bin/qmiproxy:system/bin/qmiproxy \
	vendor/samsung/expressatt/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/samsung/expressatt/proprietary/bin/rild:system/bin/rild \
	vendor/samsung/expressatt/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
	vendor/samsung/expressatt/proprietary/lib/libqmi.so:system/lib/libqmi.so \
	vendor/samsung/expressatt/proprietary/lib/libqdi.so:system/lib/libqdi.so \
	vendor/samsung/expressatt/proprietary/lib/libqdp.so:system/lib/libqdp.so \
	vendor/samsung/expressatt/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
	vendor/samsung/expressatt/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
	vendor/samsung/expressatt/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
	vendor/samsung/expressatt/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
	vendor/samsung/expressatt/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
	vendor/samsung/expressatt/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
	vendor/samsung/expressatt/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
	vendor/samsung/expressatt/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
	vendor/samsung/expressatt/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
	vendor/samsung/expressatt/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
	vendor/samsung/expressatt/proprietary/lib/hw/nfc.MSM8960.so:system/lib/hw/nfc.MSM8960.so \
	vendor/samsung/expressatt/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
	vendor/samsung/expressatt/proprietary/lib/hw/camera.vendor.msm8960.so:system/lib/hw/camera.vendor.msm8960.so \
	vendor/samsung/expressatt/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
	vendor/samsung/expressatt/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
	vendor/samsung/expressatt/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
	vendor/samsung/expressatt/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
	vendor/samsung/expressatt/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
	vendor/samsung/expressatt/proprietary/lib/libgemini.so:system/lib/libgemini.so \
	vendor/samsung/expressatt/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
	vendor/samsung/expressatt/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
	vendor/samsung/expressatt/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
	vendor/samsung/expressatt/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
	vendor/samsung/expressatt/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
	vendor/samsung/expressatt/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
	vendor/samsung/expressatt/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
	vendor/samsung/expressatt/proprietary/bin/geomagneticd:system/bin/geomagneticd \
	vendor/samsung/expressatt/proprietary/bin/orientationd:system/bin/orientationd \
	vendor/samsung/expressatt/proprietary/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so \
	vendor/samsung/expressatt/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
	vendor/samsung/expressatt/proprietary/lib/libsensor_yamaha532_test.so:system/lib/libsensor_yamaha532_test.so \
	vendor/samsung/expressatt/proprietary/bin/macloader:system/bin/macloader \
	vendor/samsung/expressatt/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00 \
	vendor/samsung/expressatt/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01 \
	vendor/samsung/expressatt/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02 \
	vendor/samsung/expressatt/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04 \
	vendor/samsung/expressatt/proprietary/etc/firmware/wcnss.b05:system/etc/firmware/wcnss.b05 \
	vendor/samsung/expressatt/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt \
	vendor/samsung/expressatt/proprietary/etc/hostapd/hostapd.accept:system/etc/hostapd/hostapd.accept \
	vendor/samsung/expressatt/proprietary/etc/hostapd/hostapd.deny:system/etc/hostapd/hostapd.deny \
	vendor/samsung/expressatt/proprietary/etc/hostapd/hostapd_default.conf:system/etc/hostapd/hostapd_default.conf \
	vendor/samsung/expressatt/proprietary/bin/btnvtool:system/bin/btnvtool \
	vendor/samsung/expressatt/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
	vendor/samsung/expressatt/proprietary/lib/libdiag.so:system/lib/libdiag.so
