# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/hltevzw/setup-makefiles.sh

PRODUCT_COPY_FILES += \
	vendor/samsung/hltevzw/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
	vendor/samsung/hltevzw/proprietary/vendor/firmware/libpn547_fw_pku.so:system/vendor/firmware/libpn547_fw_pku.so \
	vendor/samsung/hltevzw/proprietary/vendor/firmware/libpn547_fw_platform.so:system/vendor/firmware/libpn547_fw_platform.so \
	vendor/samsung/hltevzw/proprietary/lib/libsensirion_h_5.so:system/lib/libsensirion_h_5.so \
	vendor/samsung/hltevzw/proprietary/lib/libnf1.so:system/lib/libnf1.so \
	vendor/samsung/hltevzw/proprietary/lib/libnfc_log.so:system/lib/libnfc_log.so \
	vendor/samsung/hltevzw/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
	vendor/samsung/hltevzw/proprietary/lib/libril.so:system/lib/libril.so \
	vendor/samsung/hltevzw/proprietary/lib/hw/sensors.msm8974.so:system/lib/hw/sensors.msm8974.so
