# Copyright (C) 2013-2016, The CyanogenMod Project
# Copyright (C) 2017, The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/serrano-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/serrano-common/proprietary/vendor/bin/btnvtool:system/vendor/bin/btnvtool \
    vendor/samsung/serrano-common/proprietary/vendor/bin/hci_qcomm_init:system/vendor/bin/hci_qcomm_init \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libaptX_encoder.so:system/vendor/lib/libaptX_encoder.so \
    vendor/samsung/serrano-common/proprietary/vendor/bin/fm_qsoc_patches:system/vendor/bin/fm_qsoc_patches \
    vendor/samsung/serrano-common/proprietary/vendor/bin/mpdecision:system/vendor/bin/mpdecision \
    vendor/samsung/serrano-common/proprietary/vendor/bin/thermald:system/vendor/bin/thermald \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libacdbloader.so:system/vendor/lib/libacdbloader.so \
    vendor/samsung/serrano-common/proprietary/etc/firmware/a300_pfp.fw:system/etc/firmware/a300_pfp.fw \
    vendor/samsung/serrano-common/proprietary/etc/firmware/a300_pm4.fw:system/etc/firmware/a300_pm4.fw \
    vendor/samsung/serrano-common/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/samsung/serrano-common/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/samsung/serrano-common/proprietary/vendor/lib/egl/eglsubAndroid.so:system/vendor/lib/egl/eglsubAndroid.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/egl/libEGL_adreno.so:system/vendor/lib/egl/libEGL_adreno.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:system/vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/egl/libGLESv2_adreno.so:system/vendor/lib/egl/libGLESv2_adreno.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/egl/libq3dtools_adreno.so:system/vendor/lib/egl/libq3dtools_adreno.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libadreno_utils.so:system/vendor/lib/libadreno_utils.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libbccQTI.so:system/vendor/lib/libbccQTI.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libC2D2.so:system/vendor/lib/libC2D2.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libc2d30-a3xx.so:system/vendor/lib/libc2d30-a3xx.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libCB.so:system/vendor/lib/libCB.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libgsl.so:system/vendor/lib/libgsl.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libllvm-qcom.so:system/vendor/lib/libllvm-qcom.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/librs_adreno_sha1.so:system/vendor/lib/librs_adreno_sha1.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/librs_adreno.so:system/vendor/lib/librs_adreno.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libRSDriver_adreno.so:system/vendor/lib/libRSDriver_adreno.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libsc-a3xx.so:system/vendor/lib/libsc-a3xx.so \
    vendor/samsung/serrano-common/proprietary/vendor/bin/netmgrd:system/vendor/bin/netmgrd \
    vendor/samsung/serrano-common/proprietary/vendor/bin/qmuxd:system/vendor/bin/qmuxd \
    vendor/samsung/serrano-common/proprietary/vendor/bin/rmt_storage:system/vendor/bin/rmt_storage \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libdsi_netctrl.so:system/vendor/lib/libdsi_netctrl.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libqdi.so:system/vendor/lib/libqdi.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libqdp.so:system/vendor/lib/libqdp.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libxml.so:system/vendor/lib/libxml.so \
    vendor/samsung/serrano-common/proprietary/vendor/bin/radish:system/vendor/bin/radish \
    vendor/samsung/serrano-common/proprietary/vendor/bin/irsc_util:system/vendor/bin/irsc_util \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libgeofence.so:system/vendor/lib/libgeofence.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libizat_core.so:system/vendor/lib/libizat_core.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libloc_ds_api.so:system/vendor/lib/libloc_ds_api.so \
    vendor/samsung/serrano-common/proprietary/vendor/bin/geomagneticd:system/vendor/bin/geomagneticd \
    vendor/samsung/serrano-common/proprietary/vendor/lib/sensors.vendor.msm8960.so:system/vendor/lib/sensors.vendor.msm8960.so \
    vendor/samsung/serrano-common/proprietary/vendor/bin/mm-qcamera-daemon:system/vendor/bin/mm-qcamera-daemon \
    vendor/samsung/serrano-common/proprietary/vendor/lib/hw/camera.vendor.msm8960.so:system/vendor/lib/hw/camera.vendor.msm8960.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libadsprpc.so:system/vendor/lib/libadsprpc.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_imx175_antishake.so:system/vendor/lib/libchromatix_imx175_antishake.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_imx175_default_video.so:system/vendor/lib/libchromatix_imx175_default_video.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_imx175_lls.so:system/vendor/lib/libchromatix_imx175_lls.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_imx175_preview.so:system/vendor/lib/libchromatix_imx175_preview.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_imx175_zsl.so:system/vendor/lib/libchromatix_imx175_zsl.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_imx175_zsl_drama.so:system/vendor/lib/libchromatix_imx175_zsl_drama.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_imx175_zsl_panorama.so:system/vendor/lib/libchromatix_imx175_zsl_panorama.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_s5k3h5xa_antishake.so:system/vendor/lib/libchromatix_s5k3h5xa_antishake.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_s5k3h5xa_default_video.so:system/vendor/lib/libchromatix_s5k3h5xa_default_video.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_s5k3h5xa_lls.so:system/vendor/lib/libchromatix_s5k3h5xa_lls.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_s5k3h5xa_preview.so:system/vendor/lib/libchromatix_s5k3h5xa_preview.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_s5k3h5xa_zsl.so:system/vendor/lib/libchromatix_s5k3h5xa_zsl.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_s5k3h5xa_zsl_drama.so:system/vendor/lib/libchromatix_s5k3h5xa_zsl_drama.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_s5k3h5xa_zsl_panorama.so:system/vendor/lib/libchromatix_s5k3h5xa_zsl_panorama.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_s5k6a3yx_default_video.so:system/vendor/lib/libchromatix_s5k6a3yx_default_video.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_s5k6a3yx_preview.so:system/vendor/lib/libchromatix_s5k6a3yx_preview.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_s5k6a3yx_smart_stay.so:system/vendor/lib/libchromatix_s5k6a3yx_smart_stay.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_s5k6a3yx_vt.so:system/vendor/lib/libchromatix_s5k6a3yx_vt.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libchromatix_s5k6a3yx_vt_hd.so:system/vendor/lib/libchromatix_s5k6a3yx_vt_hd.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libgemini.so:system/vendor/lib/libgemini.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libimage-jpeg-dec-omx-comp.so:system/vendor/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libimage-jpeg-enc-omx-comp.so:system/vendor/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libimage-omx-common.so:system/vendor/lib/libimage-omx-common.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmercury.so:system/vendor/lib/libmercury.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmcamera_frameproc.so:system/vendor/lib/libmmcamera_frameproc.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmcamera_image_stab.so:system/vendor/lib/libmmcamera_image_stab.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmcamera_interface.so:system/vendor/lib/libmmcamera_interface.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmcamera_interface2.so:system/vendor/lib/libmmcamera_interface2.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmcamera_plugin.so:system/vendor/lib/libmmcamera_plugin.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmcamera_statsproc31.so:system/vendor/lib/libmmcamera_statsproc31.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmjpeg_interface.so:system/vendor/lib/libmmjpeg_interface.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmmpod.so:system/vendor/lib/libmmmpod.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libmmstillomx.so:system/vendor/lib/libmmstillomx.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libTsAccm.so:system/vendor/lib/libTsAccm.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libTsAwb.so:system/vendor/lib/libTsAwb.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/libqti-perfd-client.so:system/vendor/lib/libqti-perfd-client.so \
    vendor/samsung/serrano-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so
