# Copyright (C) 2012-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/i9300/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/i9300/proprietary/bin/glgps:system/bin/glgps \
    vendor/samsung/i9300/proprietary/lib/hw/gps.exynos4.vendor.so:system/lib/hw/gps.exynos4.vendor.so \
    vendor/samsung/i9300/proprietary/lib/libakm.so:system/lib/libakm.so \
    vendor/samsung/i9300/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so
