# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/d2r530/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/samsung/d2r530/proprietary/lib/libgsl.so:system/lib/libgsl.so \
        vendor/samsung/d2r530/proprietary/bin/netmgrd:system/bin/netmgrd \
        vendor/samsung/d2r530/proprietary/bin/sec-ril:system/bin/sec-ril \
        vendor/samsung/d2r530/proprietary/bin/qmiproxy:system/bin/qmiproxy \
        vendor/samsung/d2r530/proprietary/bin/qmuxd:system/bin/qmuxd \
        vendor/samsung/d2r530/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
        vendor/samsung/d2r530/proprietary/lib/libqmi.so:system/lib/libqmi.so \
        vendor/samsung/d2r530/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
        vendor/samsung/d2r530/proprietary/lib/libril.so:system/lib/libril.so \
        vendor/samsung/d2r530/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
        vendor/samsung/d2r530/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
        vendor/samsung/d2r530/proprietary/lib/libidl.so:system/lib/libidl.so \
        vendor/samsung/d2r530/proprietary/bin/rmt_storage:system/bin/rmt_storage \
        vendor/samsung/d2r530/proprietary/bin/rild:system/bin/rild \
        vendor/samsung/d2r530/proprietary/lib/libqdi.so:system/lib/libqdi.so \
        vendor/samsung/d2r530/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
        vendor/samsung/d2r530/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
        vendor/samsung/d2r530/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
        vendor/samsung/d2r530/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
        vendor/samsung/d2r530/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
        vendor/samsung/d2r530/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
        vendor/samsung/d2r530/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
        vendor/samsung/d2r530/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
        vendor/samsung/d2r530/proprietary/lib/libatparser.so:system/lib/libatparser.so \
        vendor/samsung/d2r530/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \ 
        vendor/samsung/d2r530/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so
