# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/galaxynote/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
    vendor/samsung/galaxynote-common/proprietary/libTVOut.so:obj/lib/libTVOut.so \
    vendor/samsung/galaxynote-common/proprietary/libfimc.so:obj/lib/libfimc.so

# EGL
PRODUCT_COPY_FILES += \
    vendor/samsung/galaxynote-common/proprietary/gralloc.exynos4.so:system/lib/hw/gralloc.exynos4.so \
    vendor/samsung/galaxynote-common/proprietary/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/samsung/galaxynote-common/proprietary/libGLES_android.so:system/lib/egl/libGLES_android.so \
    vendor/samsung/galaxynote-common/proprietary/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/galaxynote-common/proprietary/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/samsung/galaxynote-common/proprietary/libGLESv1_CM.so:system/lib/libGLESv1_CM.so \
    vendor/samsung/galaxynote-common/proprietary/libGLESv2.so:system/lib/libGLESv2.so \
    vendor/samsung/galaxynote-common/proprietary/libGLESv2_dbg.so:system/lib/libGLESv2_dbg.so \
    vendor/samsung/galaxynote-common/proprietary/libion.so:system/lib/libion.so \
    vendor/samsung/galaxynote-common/proprietary/libMali.so:system/lib/libMali.so \
    vendor/samsung/galaxynote-common/proprietary/libUMP.so:system/lib/libUMP.so

# HWCOMPOSER
PRODUCT_COPY_FILES += \
    vendor/samsung/galaxynote-common/proprietary/hwcomposer.exynos4.so:system/lib/hw/hwcomposer.exynos4.so \
    vendor/samsung/galaxynote-common/proprietary/bintvoutservice:system/bin/bintvoutservice \
    vendor/samsung/galaxynote-common/proprietary/libcec.so:system/lib/libcec.so \
    vendor/samsung/galaxynote-common/proprietary/libddc.so:system/lib/libddc.so \
    vendor/samsung/galaxynote-common/proprietary/libedid.so:system/lib/libedid.so \
    vendor/samsung/galaxynote-common/proprietary/libfimc.so:system/lib/libfimc.so \
    vendor/samsung/galaxynote-common/proprietary/libhdmi.so:system/lib/libhdmi.so \
    vendor/samsung/galaxynote-common/proprietary/libhdmiclient.so:system/lib/libhdmiclient.so \
    vendor/samsung/galaxynote-common/proprietary/libTVOut.so:system/lib/libTVOut.so \
    vendor/samsung/galaxynote-common/proprietary/libtvout_jni.so:system/lib/libtvout_jni.so \
    vendor/samsung/galaxynote-common/proprietary/libtvoutinterface.so:system/lib/libtvoutinterface.so \
    vendor/samsung/galaxynote-common/proprietary/libtvoutservice.so:system/lib/libtvoutservice.so

# CAMERA
PRODUCT_COPY_FILES += \
    vendor/samsung/galaxynote-common/proprietary/camera.exynos4.so:system/lib/hw/vendor-camera.exynos4.so \
    vendor/samsung/galaxynote-common/proprietary/libcaps.so:system/lib/libcaps.so \
    vendor/samsung/galaxynote-common/proprietary/datapattern_420sp.yuv:system/cameradata/datapattern_420sp.yuv \
    vendor/samsung/galaxynote-common/proprietary/datapattern_front_420sp.yuv:system/cameradata/datapattern_front_420sp.yuv

# SENSORS
PRODUCT_COPY_FILES += \
    vendor/samsung/galaxynote-common/proprietary/libakm.so:system/lib/libakm.so \
    vendor/samsung/galaxynote-common/proprietary/sensors.exynos4.so:system/lib/hw/sensors.exynos4.so

# GPS
PRODUCT_COPY_FILES += \
    vendor/samsung/galaxynote-common/proprietary/gpsd:system/bin/gpsd \
    vendor/samsung/galaxynote-common/proprietary/gps.exynos4.so:system/lib/hw/gps.exynos4.so\
    vendor/samsung/galaxynote-common/proprietary/gps.cer:system/bin/gps.cer \
    vendor/samsung/galaxynote-common/proprietary/gps.xml:system/etc/gps.xml \
# WIFI
PRODUCT_COPY_FILES += \
    vendor/samsung/galaxynote-common/proprietary/bcm4330B1.hcd:system/bin/bcm4330B1.hcd \
    vendor/samsung/galaxynote-common/proprietary/bcm4330_apsta.bin:system/etc/wifi/bcm4330_apsta.bin \
    vendor/samsung/galaxynote-common/proprietary/bcm4330_mfg.bin:system/etc/wifi/bcm4330_mfg.bin \
    vendor/samsung/galaxynote-common/proprietary/bcm4330_p2p.bin:system/etc/wifi/bcm4330_p2p.bin \
    vendor/samsung/galaxynote-common/proprietary/bcm4330_sta.bin:system/etc/wifi/bcm4330_sta.bin \
    vendor/samsung/galaxynote-common/proprietary/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/galaxynote-common/proprietary/nvram_mfg.txt_murata:system/etc/wifi/nvram_mfg.txt_murata \
    vendor/samsung/galaxynote-common/proprietary/nvram_mfg.txt_semcove:system/etc/wifi/nvram_mfg.txt_semcove \
    vendor/samsung/galaxynote-common/proprietary/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/galaxynote-common/proprietary/nvram_net.txt_murata:system/etc/wifi/nvram_net.txt_murata \
    vendor/samsung/galaxynote-common/proprietary/nvram_net.txt_semcove:system/etc/wifi/nvram_net.txt_semcove \

# NFC

# MFC Firmware
PRODUCT_COPY_FILES += \
    vendor/samsung/galaxynote-common/proprietary/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin

# LPM
PRODUCT_COPY_FILES += \
    vendor/samsung/galaxynote-common/proprietary/immvibed:system/bin/immvibed \
    vendor/samsung/galaxynote-common/proprietary/lpmkey:system/bin/lpmkey \
    vendor/samsung/galaxynote-common/proprietary/playlpm:system/bin/playlpm \
    vendor/samsung/galaxynote-common/proprietary/battery_batteryerror.qmg:system/media/battery_batteryerror.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_5.qmg:system/media/battery_charging_5.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_10.qmg:system/media/battery_charging_10.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_100.qmg:system/media/battery_charging_100.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_15.qmg:system/media/battery_charging_15.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_20.qmg:system/media/battery_charging_20.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_25.qmg:system/media/battery_charging_25.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_30.qmg:system/media/battery_charging_30.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_35.qmg:system/media/battery_charging_35.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_40.qmg:system/media/battery_charging_40.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_45.qmg:system/media/battery_charging_45.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_50.qmg:system/media/battery_charging_50.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_55.qmg:system/media/battery_charging_55.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_60.qmg:system/media/battery_charging_60.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_65.qmg:system/media/battery_charging_65.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_70.qmg:system/media/battery_charging_70.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_75.qmg:system/media/battery_charging_75.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_80.qmg:system/media/battery_charging_80.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_85.qmg:system/media/battery_charging_85.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_90.qmg:system/media/battery_charging_90.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_charging_95.qmg:system/media/battery_charging_95.qmg \
    vendor/samsung/galaxynote-common/proprietary/battery_error.qmg:system/media/battery_error.qmg \
    vendor/samsung/galaxynote-common/proprietary/chargingwarning.qmg:system/media/chargingwarning.qmg \
    vendor/samsung/galaxynote-common/proprietary/Disconnected.qmg:system/media/Disconnected.qmg \
    vendor/samsung/galaxynote-common/proprietary/LMprec_508.emd:system/media/LMprec_508.emd \
    vendor/samsung/galaxynote-common/proprietary/PFFprec_600.emd:system/media/PFFprec_600.emd

