#!/system/bin/sh
PATH="/system/bin"

setprop "net.cdma.ppp.interface" "$IFNAME"
setprop "net.$IFNAME.local-ip"   "$IPLOCAL"
setprop "net.$IFNAME.remote-ip"  "$IPREMOTE"
setprop "net.$IFNAME.dns1"       "$DNS1"
setprop "net.$IFNAME.dns2"       "$DNS2"

# FIXME
setprop ril.cdma.data_state 2

