# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gts4lv-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gts4lv gts4lvwifi,$(TARGET_DEVICE)),)

endif
