# Copyright (C) 2019-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gts4lvwifi/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/gts4lvwifi

PRODUCT_COPY_FILES += \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/ODM/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Bluetooth_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/ODM/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/General_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/ODM/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Global_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/ODM/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Handset_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/ODM/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Hdmi_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/ODM/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Headset_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/ODM/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/Speaker_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/ODM/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/ODM/workspaceFile.qwsp \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OLM/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OLM/Bluetooth_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OLM/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OLM/General_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OLM/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OLM/Global_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OLM/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OLM/Handset_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OLM/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OLM/Hdmi_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OLM/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OLM/Headset_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OLM/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OLM/Speaker_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OLM/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OLM/workspaceFile.qwsp \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OPEN/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Bluetooth_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OPEN/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/General_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OPEN/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Global_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OPEN/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Handset_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OPEN/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Hdmi_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OPEN/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Headset_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OPEN/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/Speaker_cal.acdb \
    vendor/samsung/gts4lvwifi/proprietary/vendor/etc/audconf/OPEN/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/audconf/OPEN/workspaceFile.qwsp \
    vendor/samsung/gts4lvwifi/proprietary/vendor/firmware/wlan/qca_cld/bdwlan.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/bdwlan.bin \
    vendor/samsung/gts4lvwifi/proprietary/vendor/firmware/wlan/qca_cld/bdwlan.bin_FEM:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/bdwlan.bin_FEM \
    vendor/samsung/gts4lvwifi/proprietary/vendor/firmware/wlan/qca_cld/grippower.info:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/grippower.info \
    vendor/samsung/gts4lvwifi/proprietary/vendor/firmware/wlan/qca_cld/regdb.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/regdb.bin \
    vendor/samsung/gts4lvwifi/proprietary/vendor/firmware/wlanmdsp.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/wlanmdsp.mbn
