# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/espressovzw/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/espressovzw/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/samsung/espressovzw/proprietary/bin/thermald:system/bin/thermald \
    vendor/samsung/espressovzw/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/samsung/espressovzw/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/samsung/espressovzw/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/samsung/espressovzw/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/samsung/espressovzw/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/samsung/espressovzw/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/samsung/espressovzw/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/samsung/espressovzw/proprietary/lib/hw/camera.vendor.msm8960.so:system/lib/hw/camera.vendor.msm8960.so \
    vendor/samsung/espressovzw/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/samsung/espressovzw/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
    vendor/samsung/espressovzw/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/espressovzw/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/samsung/espressovzw/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/samsung/espressovzw/proprietary/lib/libvdis.so:system/lib/libvdis.so \
    vendor/samsung/espressovzw/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/samsung/espressovzw/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/samsung/espressovzw/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/samsung/espressovzw/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/samsung/espressovzw/proprietary/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so \
    vendor/samsung/espressovzw/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/samsung/espressovzw/proprietary/lib/libmmcamera_statsproc30.so:system/lib/libmmcamera_statsproc30.so \
    vendor/samsung/espressovzw/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/samsung/espressovzw/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/samsung/espressovzw/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/samsung/espressovzw/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/samsung/espressovzw/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/samsung/espressovzw/proprietary/lib/libExtendedExtractor.so:system/lib/libExtendedExtractor.so \
    vendor/samsung/espressovzw/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/samsung/espressovzw/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/samsung/espressovzw/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/espressovzw/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/espressovzw/proprietary/lib/libgeofence.so:system/lib/libgeofence.so \
    vendor/samsung/espressovzw/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/espressovzw/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/samsung/espressovzw/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/samsung/espressovzw/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/espressovzw/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/samsung/espressovzw/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/samsung/espressovzw/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/espressovzw/proprietary/bin/ks:system/bin/ks \
    vendor/samsung/espressovzw/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/espressovzw/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/samsung/espressovzw/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/espressovzw/proprietary/bin/radish:system/bin/radish \
    vendor/samsung/espressovzw/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/espressovzw/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/samsung/espressovzw/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/espressovzw/proprietary/lib/libcordon.so:system/lib/libcordon.so \
    vendor/samsung/espressovzw/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/espressovzw/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/espressovzw/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/espressovzw/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/espressovzw/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/samsung/espressovzw/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/espressovzw/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/espressovzw/proprietary/bin/geomagneticd:system/bin/geomagneticd \
    vendor/samsung/espressovzw/proprietary/bin/orientationd:system/bin/orientationd \
    vendor/samsung/espressovzw/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/samsung/espressovzw/proprietary/lib/libakmd.so:system/lib/libakmd.so \
    vendor/samsung/espressovzw/proprietary/lib/libinvensense_hal.so:system/lib/libinvensense_hal.so \
    vendor/samsung/espressovzw/proprietary/lib/liblibmagnet.so:system/lib/liblibmagnet.so \
    vendor/samsung/espressovzw/proprietary/lib/libmllite.so:system/lib/libmllite.so \
    vendor/samsung/espressovzw/proprietary/lib/libmlplatform.so:system/lib/libmlplatform.so \
    vendor/samsung/espressovzw/proprietary/lib/libsensor_yamaha532_test.so:system/lib/libsensor_yamaha532_test.so \
    vendor/samsung/espressovzw/proprietary/lib/drm/libfwdlockengine.so:system/lib/drm/libfwdlockengine.so \
    vendor/samsung/espressovzw/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/samsung/espressovzw/proprietary/lib/liboemcrypto.so:system/lib/liboemcrypto.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libWVphoneAPI.so:system/vendor/lib/libWVphoneAPI.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libdrmdecrypt.so:system/vendor/lib/libdrmdecrypt.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/espressovzw/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/espressovzw/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/espressovzw/proprietary/etc/hostapd/hostapd.accept:system/etc/hostapd/hostapd.accept \
    vendor/samsung/espressovzw/proprietary/etc/hostapd/hostapd.deny:system/etc/hostapd/hostapd.deny \
    vendor/samsung/espressovzw/proprietary/etc/hostapd/hostapd_default.conf:system/etc/hostapd/hostapd_default.conf \
    vendor/samsung/espressovzw/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00 \
    vendor/samsung/espressovzw/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01 \
    vendor/samsung/espressovzw/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02 \
    vendor/samsung/espressovzw/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04 \
    vendor/samsung/espressovzw/proprietary/etc/firmware/wcnss.b05:system/etc/firmware/wcnss.b05 \
    vendor/samsung/espressovzw/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt
