# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/kltedv/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/kltedv/proprietary/blobs/dv/bin/efsks:system/blobs/dv/bin/efsks \
    vendor/samsung/kltedv/proprietary/blobs/dv/bin/ks:system/blobs/dv/bin/ks \
    vendor/samsung/kltedv/proprietary/blobs/dv/bin/qcks:system/blobs/dv/bin/qcks \
    vendor/samsung/kltedv/proprietary/blobs/dv/bin/qmuxd:system/blobs/dv/bin/qmuxd \
    vendor/samsung/kltedv/proprietary/blobs/dv/bin/rfs_access:system/blobs/dv/bin/rfs_access \
    vendor/samsung/kltedv/proprietary/blobs/dv/bin/rild:system/blobs/dv/bin/rild \
    vendor/samsung/kltedv/proprietary/blobs/dv/bin/rmt_storage:system/blobs/dv/bin/rmt_storage \
    vendor/samsung/kltedv/proprietary/blobs/dv/lib/libreference-ril.so:system/blobs/dv/lib/libreference-ril.so \
    vendor/samsung/kltedv/proprietary/blobs/dv/lib/libril.so:system/blobs/dv/lib/libril.so \
    vendor/samsung/kltedv/proprietary/blobs/dv/lib/libsec-ril.so:system/blobs/dv/lib/libsec-ril.so \
    vendor/samsung/kltedv/proprietary/blobs/dv/lib/libsecnativefeature.so:system/blobs/dv/lib/libsecnativefeature.so \
    vendor/samsung/kltedv/proprietary/blobs/dv/lib/libsecril-client.so:system/blobs/dv/lib/libsecril-client.so \
    vendor/samsung/kltedv/proprietary/blobs/dv/vendor/lib/libril-qcril-hook-oem.so:system/blobs/dv/vendor/lib/libril-qcril-hook-oem.so
PRODUCT_COPY_FILES += \
    vendor/samsung/kltedv/proprietary/blobs/spr/bin/efsks:system/blobs/spr/bin/efsks \
    vendor/samsung/kltedv/proprietary/blobs/spr/bin/ks:system/blobs/spr/bin/ks \
    vendor/samsung/kltedv/proprietary/blobs/spr/bin/qcks:system/blobs/spr/bin/qcks \
    vendor/samsung/kltedv/proprietary/blobs/spr/bin/qmuxd:system/blobs/spr/bin/qmuxd \
    vendor/samsung/kltedv/proprietary/blobs/spr/bin/rfs_access:system/blobs/spr/bin/rfs_access \
    vendor/samsung/kltedv/proprietary/blobs/spr/bin/rild:system/blobs/spr/bin/rild \
    vendor/samsung/kltedv/proprietary/blobs/spr/bin/rmt_storage:system/blobs/spr/bin/rmt_storage \
    vendor/samsung/kltedv/proprietary/blobs/spr/lib/libreference-ril.so:system/blobs/spr/lib/libreference-ril.so \
    vendor/samsung/kltedv/proprietary/blobs/spr/lib/libril.so:system/blobs/spr/lib/libril.so \
    vendor/samsung/kltedv/proprietary/blobs/spr/lib/libsec-ril.so:system/blobs/spr/lib/libsec-ril.so \
    vendor/samsung/kltedv/proprietary/blobs/spr/lib/libsecnativefeature.so:system/blobs/spr/lib/libsecnativefeature.so \
    vendor/samsung/kltedv/proprietary/blobs/spr/lib/libsecril-client.so:system/blobs/spr/lib/libsecril-client.so \
    vendor/samsung/kltedv/proprietary/blobs/spr/vendor/lib/libril-qcril-hook-oem.so:system/blobs/spr/vendor/lib/libril-qcril-hook-oem.so
PRODUCT_COPY_FILES += \
    vendor/samsung/kltedv/proprietary/vendor/firmware/bcm2079xB4_firmware.ncd:system/vendor/firmware/bcm2079xB4_firmware.ncd \
    vendor/samsung/kltedv/proprietary/vendor/firmware/bcm2079xB4_pre_firmware.ncd:system/vendor/firmware/bcm2079xB4_pre_firmware.ncd \
    vendor/samsung/kltedv/proprietary/vendor/firmware/bcm2079xB5_firmware.ncd:system/vendor/firmware/bcm2079xB5_firmware.ncd \
    vendor/samsung/kltedv/proprietary/vendor/firmware/bcm2079xB5_pre_firmware.ncd:system/vendor/firmware/bcm2079xB5_pre_firmware.ncd
