# Copyright (C) 2012-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/t0lte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/t0lte/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/t0lte/proprietary/bin/ks:system/bin/ks \
    vendor/samsung/t0lte/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/t0lte/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/samsung/t0lte/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/t0lte/proprietary/etc/Diag.cfg:system/etc/Diag.cfg \
    vendor/samsung/t0lte/proprietary/etc/Diag_zero.cfg:system/etc/Diag_zero.cfg \
    vendor/samsung/t0lte/proprietary/lib/libakm.so:system/lib/libakm.so \
    vendor/samsung/t0lte/proprietary/lib/libconfigdb.so:system/lib/libconfigdb.so \
    vendor/samsung/t0lte/proprietary/lib/libcsd-client.so:system/lib/libcsd-client.so \
    vendor/samsung/t0lte/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/samsung/t0lte/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/samsung/t0lte/proprietary/lib/libgeofence.so:system/lib/libgeofence.so \
    vendor/samsung/t0lte/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/samsung/t0lte/proprietary/lib/libizat_core.so:system/lib/libizat_core.so \
    vendor/samsung/t0lte/proprietary/lib/liblbs_core.so:system/lib/liblbs_core.so \
    vendor/samsung/t0lte/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/samsung/t0lte/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/samsung/t0lte/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/samsung/t0lte/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/samsung/t0lte/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/samsung/t0lte/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/samsung/t0lte/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/samsung/t0lte/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/samsung/t0lte/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/samsung/t0lte/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/samsung/t0lte/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/t0lte/proprietary/lib/libxml.so:system/lib/libxml.so
