# This file is generated by device/samsung/lentislte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/lentislte/proprietary/etc/Bluetooth_cal.acdb:system/etc/Bluetooth_cal.acdb \
    vendor/samsung/lentislte/proprietary/etc/General_cal.acdb:system/etc/General_cal.acdb \
    vendor/samsung/lentislte/proprietary/etc/Global_cal.acdb:system/etc/Global_cal.acdb \
    vendor/samsung/lentislte/proprietary/etc/Handset_cal.acdb:system/etc/Handset_cal.acdb \
    vendor/samsung/lentislte/proprietary/etc/Hdmi_cal.acdb:system/etc/Hdmi_cal.acdb \
    vendor/samsung/lentislte/proprietary/etc/Headset_cal.acdb:system/etc/Headset_cal.acdb \
    vendor/samsung/lentislte/proprietary/etc/Speaker_cal.acdb:system/etc/Speaker_cal.acdb
