# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/jactivelte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
        vendor/samsung/jactivelte/proprietary/mmparser/vendor/lib/libmmparser.so:system/vendor/lib/libmmparser.so \
        vendor/samsung/jactivelte/proprietary/mmparser/vendor/lib/libdivxdrm.so:system/vendor/lib/libdivxdrm.so \
        vendor/samsung/jactivelte/proprietary/mmparser/vendor/lib/libExtendedExtractor.so:system/vendor/lib/libExtendedExtractor.so \
        vendor/samsung/jactivelte/proprietary/mmparser/vendor/lib/libmmosal.so:system/vendor/lib/libmmosal.so \
        vendor/samsung/jactivelte/proprietary/mmparser/vendor/lib/libI420colorconvert.so:system/vendor/lib/libI420colorconvert.so \
        vendor/samsung/jactivelte/proprietary/mmparser/vendor/lib/libmm-color-convertor.so:system/vendor/lib/libmm-color-convertor.so
