# Copyright (C) 2014-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/trltevzw/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/trltevzw/proprietary/bin/efsks:system/bin/efsks \
    vendor/samsung/trltevzw/proprietary/bin/ks:system/bin/ks \
    vendor/samsung/trltevzw/proprietary/bin/mdm_helper:system/bin/mdm_helper \
    vendor/samsung/trltevzw/proprietary/bin/mdm_helper_proxy:system/bin/mdm_helper_proxy \
    vendor/samsung/trltevzw/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/samsung/trltevzw/proprietary/bin/qcks:system/bin/qcks \
    vendor/samsung/trltevzw/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/samsung/trltevzw/proprietary/lib/libagc_max.so:system/lib/libagc_max.so \
    vendor/samsung/trltevzw/proprietary/lib/libbt-aptX-ARM-4.2.2.so:system/lib/libbt-aptX-ARM-4.2.2.so \
    vendor/samsung/trltevzw/proprietary/lib/libbt-codec_aptx.so:system/lib/libbt-codec_aptx.so \
    vendor/samsung/trltevzw/proprietary/lib/libbt-codec_sshd.so:system/lib/libbt-codec_sshd.so \
    vendor/samsung/trltevzw/proprietary/lib/libbt-iopdb.so:system/lib/libbt-iopdb.so \
    vendor/samsung/trltevzw/proprietary/lib/libbt-iopdb_mod.so:system/lib/libbt-iopdb_mod.so \
    vendor/samsung/trltevzw/proprietary/lib/libbt-vendor.so:system/lib/libbt-vendor.so \
    vendor/samsung/trltevzw/proprietary/lib/libedmnativehelper.so:system/lib/libedmnativehelper.so \
    vendor/samsung/trltevzw/proprietary/lib/libjpegdhw.so:system/lib/libjpegdhw.so \
    vendor/samsung/trltevzw/proprietary/lib/libjpegehw.so:system/lib/libjpegehw.so \
    vendor/samsung/trltevzw/proprietary/lib/libprotobuf-cpp-full.so:system/lib/libprotobuf-cpp-full.so \
    vendor/samsung/trltevzw/proprietary/lib/libqdutils.so:system/lib/libqdutils.so \
    vendor/samsung/trltevzw/proprietary/lib/libqservice.so:system/lib/libqservice.so \
    vendor/samsung/trltevzw/proprietary/lib/libsec-ril.so:system/lib/libsec-ril.so \
    vendor/samsung/trltevzw/proprietary/lib/libshdace.so:system/lib/libshdace.so \
    vendor/samsung/trltevzw/proprietary/lib/libtinyxml.so:system/lib/libtinyxml.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libcneapiclient.so:system/vendor/lib/libcneapiclient.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libconfigdb.so:system/vendor/lib/libconfigdb.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libdiag.so:system/vendor/lib/libdiag.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libdsutils.so:system/vendor/lib/libdsutils.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libidl.so:system/vendor/lib/libidl.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libmdmdetect.so:system/vendor/lib/libmdmdetect.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libnetmgr.so:system/vendor/lib/libnetmgr.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libqcci_legacy.so:system/vendor/lib/libqcci_legacy.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libqmi.so:system/vendor/lib/libqmi.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libqmi_cci.so:system/vendor/lib/libqmi_cci.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libqmi_client_qmux.so:system/vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libqmi_common_so.so:system/vendor/lib/libqmi_common_so.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libqmi_csi.so:system/vendor/lib/libqmi_csi.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libqmi_encdec.so:system/vendor/lib/libqmi_encdec.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libqmiservices.so:system/vendor/lib/libqmiservices.so \
    vendor/samsung/trltevzw/proprietary/vendor/lib/libril-qcril-hook-oem.so:system/vendor/lib/libril-qcril-hook-oem.so
